version: '3'

services:
    # front:
    #     build:
    #       context: front
    #       args:
    #         BACK_HOST: http://${BACK_HOST}:${BACK_PORT}
    #     ports:
    #         - ${FRONT_PORT}:80
    #     restart: on-failure
    #     networks:
    #         - api-network

    api:
        build: API
        depends_on:
            - db
        ports:
            - 80:5000
        restart: on-failure
        environment:
            - DB_USER
            - DB_PASSWORD
            - DB_HOST
            - DB_PORT
            - AREA_VERSION
            - REDDIT_CLIENT_ID
            - REDDIT_CLIENT_SECRET
            - REDDIT_REDIRECT_URI
            - SPOTIFY_CLIENT_ID
            - SPOTIFY_CLIENT_SECRET
            - SPOTIFY_REDIRECT_URI
            - GITHUB_CLIENT_ID
            - GITHUB_CLIENT_SECRET
            - GITHUB_REDIRECT_URI
            - GITHUB_STATE
        networks:
            - db-network
        profiles: ["api", "production"]

    db:
        image: "postgres:alpine"
        restart: on-failure
        environment:
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        ports:
            - 5432:5432
        networks:
            - db-network
        volumes:
            - ./schema.sql://docker-entrypoint-initdb.d/schema.sql
            - db-data:/var/lib/postgresql/data
        profiles: ["api", "production"]

    mock-api:
        build: mock-api
        ports:
            - 80:12000
        restart: on-failure
        profiles: ["mock"]

    vue-front:
        build: vue-front
        ports:
            - 8080:80
        environment:
            - HOST=${FRONT_HOST}
            - PORT=${FRONT_PORT}
            - API_HOST
            - API_PORT
            - REDDIT_CLIENT_ID
            - GITHUB_CLIENT_ID
            - SPOTIFY_CLIENT_ID
        restart: on-failure
        profiles: ["front", "production"]

networks:
    db-network:

volumes:
    db-data:
