version: '3'

services:
    # front:
    #     build:
    #       context: front
    #       args:
    #         BACK_HOST: http://${BACK_HOST}:${BACK_PORT}
    #     ports:
    #         - ${FRONT_PORT}:80
    #     restart: on-failure
    #     networks:
    #         - api-network

    api:
        build: API
        ports:
            - 5000:80
        restart: on-failure
        environment:
            - DB_USER
            - DB_PASSWORD
            - DB_HOST
            - DB_PORT
        networks:
            - db-network
        profiles: ["api"]

    db:
        image: "postgres:alpine"
        restart: on-failure
        environment:
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        ports:
            - 5432:5432
        networks:
            - db-network
        volumes:
            - ./schema.sql://docker-entrypoint-initdb.d/schema.sql
            - db-data:/var/lib/postgresql/data
        profiles: ["api"]

    mock-api:
        build: mock-api
        ports:
            - 80:12000
        restart: on-failure
        profiles: ["mock"]

networks:
    db-network:
    api-network:

volumes:
    db-data:
