FROM node:lts-alpine as build
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY babel.config.js package.json package-lock.json tsconfig.json vue.config.js .eslintrc.js ./
COPY src ./src/
COPY public ./public/
RUN npm run build

FROM nginx:stable-alpine as prod
COPY --from=build /app/dist /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
